//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerJobRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerJobRequest()
        {
            this.Job = new HashSet<Job>();
        }
    
        public int Id { get; set; }
        public string JobName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Contact { get; set; }
        public string ServiceAddress { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public string ServiceDetails { get; set; }
        public Nullable<decimal> CustomerBudget { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> ReturnScheduleDate { get; set; }
        public Nullable<int> JobStatusId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual JobStatus JobStatus { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Job { get; set; }
    }
}
