//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoice
    {
        public int InvoiceKey { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string WorkPerformed { get; set; }
        public Nullable<int> JobKey { get; set; }
        public Nullable<int> CustomerKey { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    }
}
