//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public Nullable<int> JobRequestId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<decimal> VendorCharge { get; set; }
        public string MeterialDescription { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<int> JobStatusId { get; set; }
    
        public virtual CustomerJobRequest CustomerJobRequest { get; set; }
        public virtual JobStatus JobStatus { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
