//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.CustomerInvoice = new HashSet<CustomerInvoice>();
            this.VendorInvoice = new HashSet<VendorInvoice>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VndorId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> JobRequestId { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> ServiceDescription { get; set; }
        public Nullable<int> JobStatusId { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> VendorStartingDate { get; set; }
        public Nullable<System.DateTime> VendorCompletionDate { get; set; }
        public Nullable<System.DateTime> JobCompletedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerJobRequest CustomerJobRequest { get; set; }
        public virtual JobStatus JobStatus { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInvoice> CustomerInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorInvoice> VendorInvoice { get; set; }
    }
}
